server:
  port: ${dev.dev3Port}
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${dev.host}:${dev.dev1Port}/eureka,http://${dev.host}:${dev.dev2Port}/eureka
