spring:
  application:
    name: consumer-demo-hystrix
server:
  port: 8090
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 15000 #1000毫秒
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000 #1000毫秒

